services:
  storage:
    container_name: storage
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      # This is called when Localstack container is starting up.
      # Using this for AWS CLI commands currently.
      - ./storage/init-scripts/init-localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
      - ./storage/init-scripts/dynamodb-table-definition.json:/opt/code/localstack/dynamodb-table-definition.json
      - ./storage/init-scripts/data/:/opt/code/localstack/data/

  app:
    build: .
    ports:
      - "3600:3600"
    environment:
      - APP_ENV=dev
